# Generated by Django 4.2.6 on 2023-10-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_medecin_last_login_patient_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
