# Generated by Django 4.2.6 on 2023-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_oademe_autresymptome_oedeme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autresymptome",
            name="duree_douleur_thoracique_en_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="duree_malaise_en_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="duree_palpitation_en_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
