# Generated by Django 4.2.6 on 2023-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_reponse_id_reponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitephysique",
            name="id_activite_physique",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="alimentation",
            name="id_alimentation",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="id_autre_symptome",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="id_evaluation_niveau_stress",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="informationcardiaque",
            name="id_information_cardiaque",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="physique",
            name="id_physique",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="prisemedicament",
            name="id_prise_medicament",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
