# Generated by Django 4.2.6 on 2023-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_activitephysique_id_activite_physique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitephysique",
            name="activite_physique_journee_en_cours",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
