# Generated by Django 4.2.6 on 2023-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_activitephysique_activite_physique_journee_en_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentation",
            name="consommation_alcool",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="alimentation",
            name="grignotage_sale",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="alimentation",
            name="grignotage_sucre",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
    ]
