# Generated by Django 4.2.6 on 2023-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_alimentation_consommation_alcool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autresymptome",
            name="douleur_thoracique",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="dyspnee",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="episode_infectieux",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="fievre",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="malaise",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="oedeme",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="palpitation",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
    ]
