# Generated by Django 4.2.6 on 2023-11-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_autresymptome_debut_douleur_thoracique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autresymptome",
            name="debut_douleur_thoracique",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="debut_malaise",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autresymptome",
            name="debut_palpitation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
