# Generated by Django 4.2.6 on 2023-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_activitephysique_activite_physique_journee_en_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitephysique",
            name="activite_physique_journee_en_cours",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="action_geste_impulsif",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="attaque_verbale",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="begaiement_ou_hesitation_verbale",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="besoin_frequent_uriner",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="bouche_gorge_seche",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="cauchermars",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="conflit_avec_les_autres",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="debit_plus_rapide",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="diarrhee",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_a_rester_assis",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_a_se_lever_post_sommeil",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_activite_longue_continue",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_digerer",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_dormir",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_endormissement",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_incapacite_concentration",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_organiser_pensee",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="difficulte_post_contrariete",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="douleur_dos_nuque",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="douleur_serrement_poitrine",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="fatigue_ou_lourdeur_generalise",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="geste_ou_sentiment_imaptience",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="grande_envie_de_faire_mal",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="grande_envie_de_fuir",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="grande_envie_de_pleurer",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="grincement_des_dents",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="haut_bas_emotif",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="hostilite_envers_les_autres",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="irritabilite",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="main_moite",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="maux_de_tete",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="maux_estomac",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="mouvement_retrait_isolement",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="oublis_frequents",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="pensees_embrouillees",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="perte_gain_appetit",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="perte_interet_sexe",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="sentiment_de_anxiete",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="sentiment_de_etre_emotivement_fragile",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="sentiment_de_etre_surchager",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="sentiment_de_tristesse",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="sentiment_depressif",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="sentiment_hors_de_controle",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="tension_emotionnelle",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationniveaustress",
            name="tremblement_ou_geste_nerveux",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "n’est pas apparu"),
                    (1, "apparu une ou deux fois seulement"),
                    (5, "est apparu plusieurs fois"),
                    (10, "est apparu presque continuellement"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prisemedicament",
            name="effet_secondaire",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="prisemedicament",
            name="oublie_medic_matin",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="prisemedicament",
            name="oublie_medic_soir",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="prisemedicament",
            name="symptome_particulier",
            field=models.IntegerField(
                blank=True, choices=[(1, "Oui"), (0, "Non")], null=True
            ),
        ),
    ]
