# Generated by Django 4.2.6 on 2023-11-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0018_alter_activitephysique_activite_physique_journee_en_cours_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="medecin",
            name="tel_medecin",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
